//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.22 at 03:09:06 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://slick.com/service2", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.SlicK.service2;
