//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.22 at 03:00:35 PM EEST 
//


package com.SlicK.service1;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.slick.service1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.slick.service1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.SlicK.service1.GetCustomerRequest }
     * 
     */
    public com.SlicK.service1.GetCustomerRequest createGetCustomerRequest() {
        return new com.SlicK.service1.GetCustomerRequest();
    }

    /**
     * Create an instance of {@link com.SlicK.service1.GetCustomerResponse }
     * 
     */
    public com.SlicK.service1.GetCustomerResponse createGetCustomerResponse() {
        return new com.SlicK.service1.GetCustomerResponse();
    }

}
